obj-$(CONFIG_INTELLI_PLUG)	:= intelli_plug.o
obj-$(CONFIG_MSM_HOTPLUG)         += msm_hotplug.o
obj-$(CONFIG_BRICKED_HOTPLUG)     += bricked_hotplug.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o
obj-$(CONFIG_ZEN_DECISION)        += msm_zen_decision.o

